services:
  db:
    image: postgres:16
    container_name: financial-analyzer-db
    environment:
      POSTGRES_DB: financial_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml-service:
    build:
      context: ./ml-service
    container_name: financial-analyzer-ml
    ports:
      - "8000:8000"

  app:
    build:
      context: ./financial-analyzer
    container_name: financial-analyzer-backend
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/financial_analyzer
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      APP_ADMIN_USER: ${APP_ADMIN_USER}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      ML_SERVICE_URL: http://ml-service:8000/predict
    depends_on:
      - db
      - ml-service

volumes:
  postgres_data: