name: Java CI - Financial Analyzer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give execute permission to Maven wrapper
        working-directory: financial-analyzer
        run: chmod +x mvnw

      - name: Build backend
        working-directory: financial-analyzer
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        working-directory: financial-analyzer
        run: docker build -t financial-analyzer .